language: python

matrix:
  allow_failures:
    - python: nightly
  include:
    - python: 2.7
      arch: arm64
    - python: 2.7
      arch: amd64
    - python: 3.4
      arch: arm64
      dist: trusty
    - python: 3.4
      arch: amd64
      dist: trusty
    - python: 3.5
      arch: arm64
    - python: 3.5
      arch: amd64
    - python: 3.6
      arch: arm64
    - python: 3.6
      arch: amd64
    - python: 3.7
      arch: arm64
      dist: xenial
    - python: 3.7
      arch: amd64
      dist: xenial
    - python: 3.8
      arch: arm64
      dist: xenial
    - python: 3.8
      arch: amd64
      dist: xenial
    - python: nightly
      arch: arm64
    - python: nightly
      arch: amd64
    - python: pypy
      arch: arm64
    - python: pypy
      arch: amd64
    # linux wheels
    - dist: trusty
      sudo: required
      services:
        - docker
      env: XXTEA_BUILDWHEELS=1
    # osx wheels
    - os: osx
      osx_image: xcode9.4
      language: generic
      env: XXTEA_BUILDWHEELS=1
      before_install:
        - SSL_CERT_FILE=$(brew --prefix)/etc/openssl/cert.pem
        - sudo pip install -U pip setuptools twine

install:
  - gcc --version
  - |
    if [ -n "${XXTEA_BUILDWHEELS:-}" ]; then
      pip install cibuildwheel
    fi

script:
  - |
    if [ -n "${XXTEA_BUILDWHEELS:-}" ]; then
      cibuildwheel --output-dir dist
    else
      python setup.py test
    fi

after_success: bash bench.sh

before_deploy: ls dist/

deploy:
  # deploy master non-tags to Test PyPI
  - provider: pypi
    user: ifduyue
    password:
      secure: "ctdbAphV76iJ6LajtlE24kFXuA0/tgVTVF2MmiDjJnO5r3T+nHb7rw5lpR/gW0zuhj9fwebZFdzOi2+HCeiZIrnd0pneplYkJC2a/e+oCrLR/I0MsS9fKgDlJzNlcE9pZj3l7KzuFnm7uC/k6DfjnA1v4kOIAda60G/KDkx+V2E="
    server: https://test.pypi.org/legacy/
    distributions: sdist
    skip_existing: true
    skip_cleanup: true
    on:
      repo: ifduyue/xxtea
      tags: false
      branch: master
      condition: -n "${XXTEA_BUILDWHEELS:-}"

  # deploy tags to PyPI
  - provider: pypi
    user: ifduyue
    password:
      secure: "pzPG0jSJqOCYYZ7yTgtlfk+LZ8BO0H3ALJx8Da7XPvi2hyjpV+HiqMiMK+hZIclljLMiF5ydRLqadyvHbqN68W2rAOqqLjxe9qdoYdBB55zM5sG9+eII/HNj7qj2qdhj6IEQSrzKkXROcfQCNpJWjpa1NetxgE8TSmaG7ysziGA="
    distributions: sdist
    skip_existing: true
    skip_cleanup: true
    on:
      repo: ifduyue/xxtea
      tags: true
      condition: -n "${XXTEA_BUILDWHEELS:-}"
