name: Build and upload to PyPI

on: [push]

jobs:
  build_wheels:
    name: Build ${{ matrix.archs }} ${{ matrix.build }} wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04]
        archs: ["x86_64, i686", "aarch64", "ppc64le", "s390x", "riscv64", "armv7l"]
        build: ["manylinux", "musllinux"]
        platform: ["auto"]
        include:
          - os: windows-2022
            archs: "AMD64"
          - os: windows-2022
            archs: "x86"
          - os: windows-2022
            archs: "ARM64"
          - os: macos-13
            archs: "x86_64, arm64"
          #- os: ubuntu-22.04
          #  archs: "wasm32"
          #  platform: "pyodide"
          - os: ubuntu-22.04
            archs: "arm64_v8a, x86_64"
            platform: "android"
          - os: macos-14
            archs: "arm64_iphoneos,arm64_iphonesimulator"
            platform: "ios"
          - os: macos-13
            archs: "x86_64_iphonesimulator"
            platform: "ios"

    steps:
      - name: Disable git autocrlf
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf

      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        if: runner.os == 'Linux'

      - name: Build wheels
        uses: pypa/cibuildwheel@v3.3.1
        env:
          CIBW_ARCHS: "${{ matrix.archs }}"
          CIBW_BUILD: "${{ matrix.build && '*-' || ''}}${{ matrix.build }}*"
          CIBW_PLATFORM: "${{ matrix.platform }}"
          CIBW_PRERELEASE_PYTHONS: "${{ !startsWith(github.ref, 'refs/tags/v') }}"

      - uses: actions/upload-artifact@v6
        with:
          name: wheels-${{ matrix.os }}-${{ matrix.build }}-${{ matrix.archs }}
          path: ./wheelhouse/*.whl


  build_sdist:
    name: Build sdist
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python-version: ['3.10']
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: python -m pip install -U pip 'setuptools>=45'

      - name: Build sdist
        run: python setup.py build sdist

      - uses: actions/upload-artifact@v6
        with:
          name: wheels-dist
          path: dist/*.tar.gz


  upload_test_pypi:
    name: Upload to Test PyPI
    needs: [build_wheels, build_sdist]
    runs-on: ubuntu-22.04
    if: github.event_name == 'push' && github.repository == 'ifduyue/xxtea' && !startsWith(github.ref, 'refs/tags/v')
    environment:
      name: test-pypi
      url: https://test.pypi.org/project/xxtea/
    permissions:
      id-token: write
    steps:
      - uses: actions/download-artifact@v7
        with:
          pattern: wheels-*
          path: dist
          merge-multiple: true

      - name: Upload to Test PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          skip-existing: true
          repository-url: https://test.pypi.org/legacy/

  upload_pypi:
    name: Upload to PyPI
    needs: [build_wheels, build_sdist]
    runs-on: ubuntu-22.04
    if: github.event_name == 'push' && github.repository == 'ifduyue/xxtea' && startsWith(github.ref, 'refs/tags/v')
    environment:
      name: pypi
      url: https://pypi.org/project/xxtea/
    permissions:
      id-token: write
    steps:
      - uses: actions/download-artifact@v7
        with:
          pattern: wheels-*
          path: dist
          merge-multiple: true

      - name: Upload to PyPI
        if: startsWith(github.ref, 'refs/tags/v')
        uses: pypa/gh-action-pypi-publish@release/v1
